version: 2.1
description: Validate and format Terraform files
orbs:
  terraform: "circleci/terraform@3.2.1"
  tflint: orbies/terraform@8.1.0
workflows:
  format_terraform:
    jobs:
      - terraform/fmt:
          checkout: true
  lint_terraform:
    jobs:
      - tflint/lint:
          checkout: true
          config_file: .tflint.hcl
          working_directory: ./
          environtment:
            TFLINT_LOG: debug
