version: 2.1
description: Validate and format Terraform files
orbs:
  terraform: "dnd-it/terraform@3.1"
workflows:
  format_terraform:
    jobs:
      - terraform/fmt
      - terraform/tflint:
          tflint_cli_args: "--config=.tflint.hcl"